resources:
  - url: http://127.0.0.1:5000/hourly-weather-card.js
    type: module
views:
  - cards:
      - type: custom:hourly-weather
        name: Hourly Weather Card Development
        entity: weather.home
        test_gui: true
